version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: express_app
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/db"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      GEMINI_KEY: ${GEMINI_KEY}
    volumes:
      - .:/usr/src/app
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
